// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrQY1844KgyHEw2lkGV4im5PXa96aL1TY',
    appId: '1:415033030230:web:4d87c1a04d50549070edf7',
    messagingSenderId: '415033030230',
    projectId: 'auri-app-77770',
    authDomain: 'auri-app-77770.firebaseapp.com',
    storageBucket: 'auri-app-77770.firebasestorage.app',
    measurementId: 'G-BMB8KYZ1S3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABcoK9k_VCKj7AuthPcgjyS998q-_3xD0',
    appId: '1:415033030230:android:125132cb882b6e2570edf7',
    messagingSenderId: '415033030230',
    projectId: 'auri-app-77770',
    storageBucket: 'auri-app-77770.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwyTUJeXllau8XNe5t3CCwa4AwQrRemPc',
    appId: '1:415033030230:ios:5e5559ee2bcc663670edf7',
    messagingSenderId: '415033030230',
    projectId: 'auri-app-77770',
    storageBucket: 'auri-app-77770.firebasestorage.app',
    iosBundleId: 'com.ivgroup.auriapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwyTUJeXllau8XNe5t3CCwa4AwQrRemPc',
    appId: '1:415033030230:ios:6b498ba2465b16d370edf7',
    messagingSenderId: '415033030230',
    projectId: 'auri-app-77770',
    storageBucket: 'auri-app-77770.firebasestorage.app',
    iosBundleId: 'com.example.auriapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrQY1844KgyHEw2lkGV4im5PXa96aL1TY',
    appId: '1:415033030230:web:e26617ab9329455f70edf7',
    messagingSenderId: '415033030230',
    projectId: 'auri-app-77770',
    authDomain: 'auri-app-77770.firebaseapp.com',
    storageBucket: 'auri-app-77770.firebasestorage.app',
    measurementId: 'G-2EL79B4DVR',
  );

}